# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-VCard-LDAP
version:      0.03
version_from: lib/DJabberd/Plugin/VCard/LDAP.pm
installdirs:  site
requires:
    DJabberd:                      0.83
    DJabberd::Plugin::VCard:       0
    Net::LDAP:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
