--- #YAML:1.0
name:                DJabberd-VCard-LDAP
version:             0.04
abstract:            LDAP VCard Provider for DJabberd
license:             ~
author:              
    - Edward Rudd <urkle@outoforder.cc>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DJabberd:                      0.83
    DJabberd::Plugin::VCard:       0
    Net::LDAP:                     0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
